name: "publish"

on:
  push:
    branches: "**"
    tags-ignore: ["**"]
  release:
    types: [ "released" ]
  workflow_dispatch:

permissions:
  contents: "read"

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - name: "setup"
        id: "setup"
        uses: "KyoriPowered/.github/.github/actions/setup-python-env@trunk"
      - name: "setup / install deps"
        run: "poetry install"
      - name: "build wheel"
        run: "poetry build"
      - name: "upload artifact"
        uses: "actions/upload-artifact@v4.6.0"
        with:
          name: "python-package-distributions"
          path: "dist/"
  publish-to-pypi:
    if: "${{ github.event_name == 'release' }}"
    runs-on: "ubuntu-latest"
    needs: "build"
    permissions:
      id-token: "write"
    environment:
      name: "pypi"
      url: "https://pypi.org/p/pygments-minimessage"
    steps:
      - name: "download artifact"
        uses: "actions/download-artifact@v4.1.8"
        with:
          name: "python-package-distributions"
          path: "dist/"
      - name: "publish / pypi"
        uses: "pypa/gh-action-pypi-publish@v1.12.4"
      - name: "publish / release"
        uses: "softprops/action-gh-release@v2.2.1"
        with:
          files: |
            dist/**
  publish-to-testpypi:
    if: "${{ github.event_name == 'workflow_dispatch' }}"
    runs-on: "ubuntu-latest"
    needs: "build"
    permissions:
      id-token: "write"
    environment:
      name: "testpypi"
      url: "https://test.pypi.org/p/pygments-minimessage"
    steps:
      - name: "download artifact"
        uses: "actions/download-artifact@v4.1.8"
        with:
          name: "python-package-distributions"
          path: "dist/"
      - name: "publish / testpypi"
        uses: "pypa/gh-action-pypi-publish@v1.12.4"
        with:
          repository-url: "https://test.pypi.org/legacy/"
          verbose: true
